name: Build Android APK
on: [push] # Sen her kod yüklediğinde Ubuntu otomatik açılır
jobs:
  build:
    runs-on: ubuntu-latest # İşte Ubuntu burada kuruluyor!
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Android SDK & Buildozer
        run: |
          sudo apt update
          sudo apt install -y git zip unzip autoconf autogen libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          pip install --user --upgrade buildozer cython virtualenv
